# Generated by Django 5.2.1 on 2026-06-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDim',
            fields=[
                ('id_company', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.TextField()),
                ('workforce_size', models.TextField(null=True)),
                ('sector', models.TextField(null=True)),
            ],
            options={
                'db_table': 'd_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CountryDim',
            fields=[
                ('id_country', models.AutoField(primary_key=True, serialize=False)),
                ('iso2', models.CharField(max_length=2, unique=True)),
                ('country_name', models.TextField()),
                ('region', models.TextField(null=True)),
                ('monnaie_iso3', models.CharField(max_length=3, null=True)),
            ],
            options={
                'db_table': 'd_country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DateDim',
            fields=[
                ('date_key', models.DateField(primary_key=True, serialize=False)),
                ('day', models.SmallIntegerField()),
                ('month', models.SmallIntegerField()),
                ('quarter', models.SmallIntegerField()),
                ('year', models.SmallIntegerField()),
                ('day_week', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'd_date',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactJob',
            fields=[
                ('id_fact', models.AutoField(primary_key=True, serialize=False)),
                ('avg_salary', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('job_count', models.IntegerField()),
            ],
            options={
                'db_table': 'fact_job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SkillDim',
            fields=[
                ('id_skill', models.AutoField(primary_key=True, serialize=False)),
                ('tech_label', models.TextField()),
                ('skill_group', models.TextField(null=True)),
            ],
            options={
                'db_table': 'd_skill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SourceDim',
            fields=[
                ('id_source', models.AutoField(primary_key=True, serialize=False)),
                ('source_name', models.TextField()),
            ],
            options={
                'db_table': 'd_source',
                'managed': False,
            },
        ),
    ]
